import ProgressProvider from "@/components/progressbar";
import "./globals.css";
import localFont from "next/font/local";
import LayoutWrapper from "@/components/layoutwrapper";
import { Toaster } from "react-hot-toast";
import { UserProvider } from "@/context/userContext";

const circularStd = localFont({
  src: [
    {
      path: "./fonts/circular/CircularStd-Black.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/circular/CircularStd-BlackItalic.ttf",
      weight: "900",
      style: "italic",
    },
    {
      path: "./fonts/circular/CircularStd-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/circular/CircularStd-BoldItalic.otf",
      weight: "700",
      style: "italic",
    },
    {
      path: "./fonts/circular/CircularStd-Book.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/circular/CircularStd-BookItalic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/circular/CircularStd-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/circular/CircularStd-MediumItalic.ttf",
      weight: "500",
      style: "italic",
    },
  ],
  display: "swap",
  variable: "--font-circular",
});

const tinos = localFont({
  src: [
    {
      path: "./fonts/tinos/Tinos-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/tinos/Tinos-BoldItalic.ttf",
      weight: "700",
      style: "italic",
    },
    {
      path: "./fonts/tinos/Tinos-Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/tinos/Tinos-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-tinos",
});

export const metadata = {
  title: "Simpliyfy-Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${circularStd.variable} ${tinos.variable}`}>
        <UserProvider>
          <LayoutWrapper>
            <ProgressProvider>{children}</ProgressProvider>
            <Toaster
              toastOptions={{
                className: "font-circular  !max-w-[500px] tracking-wide",
              }}
              position="bottom-right"
            />
          </LayoutWrapper>
        </UserProvider>
      </body>
    </html>
  );
}
